- lib/lnurl.ts
> fix: prioritize parsing of lightning addresses over lnurls

- lib/state/appStore.ts
- pages/settings/wallets/DemoWallets.tsx
- pages/settings/wallets/EditWallet.tsx
- pages/settings/wallets/WalletConnection.tsx
Adds a warning in the edit wallet page if you use a demo wallet, and recommends Alby Hub. Also adds a way to export the connection secret
> feat: demo wallet warning and export connection secret

- pages/send/Send.tsx
- pages/settings/Wallets.tsx
- Allow users to use the app without camera permissions (show buttons below camera)
- After you repeatedly denied camera permissions the permission requests will stop working on Android (you need to go to the app settings to reset it I think, don't know the behavior on iOS)
- Don't know if we still need the screen asking you to grant permissions (on Android that happens automatically via the useEffect() call)
> feat: camera permissions

- pages/settings/wallets/EditWallet.tsx
The wallet connection settings are currently a bit confusing for the average user, we might want to rethink what a user would want to see in there. 
We should also think about removing the option to "disconnect" a wallet (remove the connection string) maybe, it doesn't make much sense to me to separate these two entities.
> fix: remove wallet connection settings link

- eas.json
Allows to create multiple releases in stores with the same tag (e.g. 1.4.0) as the internal build number is increased.
> fix: load internal build numbers from eas 

- pages/settings/wallets/WalletConnection.tsx
Fixes https://github.com/getAlby/go/issues/78
This is why nwc.getalby.com and lifpay break with Alby Go
> fix: do not crash if NWC connection does not support notifications

- components/ToastConfig.tsx
- hooks/useBalance.ts
- hooks/useInfo.ts
- hooks/useTransactions.ts
- lib/errorToast.ts
- lib/swr.ts
- pages/receive/Receive.tsx
- pages/send/ConfirmPayment.tsx
- pages/send/LNURLPay.tsx
- pages/send/Send.tsx
- pages/settings/wallets/WalletConnection.tsx
previously we do not properly catch errors in the swr methods so we could not show an error toast when something went wrong.
errorToast also threw an uncaught exception if it did not receive an error object, which lead to the app hanging
> fix: error handling

- app/_layout.tsx
- components/Icons.tsx
- components/ui/dialog.tsx
- package.json
- pages/settings/Settings.tsx
- pages/settings/wallets/WalletConnection.tsx
- yarn.lock
> feat: add infos about how to connect

- components/DismissableKeyboardView.tsx
- pages/receive/Receive.tsx
- pages/send/LNURLPay.tsx
- pages/send/Send.tsx
- pages/settings/FiatCurrency.tsx
- pages/settings/address-book/NewAddressBookEntry.tsx
- pages/settings/wallets/LightningAddress.tsx
- pages/settings/wallets/NewWallet.tsx
- pages/settings/wallets/RenameWallet.tsx
Fixes #41
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/2e788971-5b26-4e49-b14f-4c42e402041d" width="100%"></td>
<td><img src="https://github.com/user-attachments/assets/e1f514ec-6cdf-4789-98f0-aa88de5fb802" width="100%"></td>
<td><img src="https://github.com/user-attachments/assets/7f90973c-1682-4eb8-9f59-e207253b183e" width="100%"></td>
<td><img src="https://github.com/user-attachments/assets/fea53051-ef57-4ace-bb4d-de3686725fc8" width="100%"></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/08b97e63-5a4f-4dd2-88e7-69db6d473ca4" width="100%"></td>
<td><img src="https://github.com/user-attachments/assets/efc7104b-fbde-4302-9eb8-f4ebddc453d6" width="100%"></td>
<td><img src="https://github.com/user-attachments/assets/e7b0a66d-f0ad-4d57-9e9c-6 …
> fix: adjust keyboard behavior for iOS using KeyboardAvoidingView

- pages/Transaction.tsx
Fixes #93 
Payment hash + preimage are now "touchable", means as soon as you press it the content is copied to clipboard and you'll see some visual feedback. 
I think it's better for a user than fiddling around with text selection on mobile.
> fix: copy preimage & payment hash

- pages/settings/FiatCurrency.tsx
Changing fiat currency was not working for me because the state variable was not being updated, best to set it from the parameter itself
> fix: use parameter instead of state variable while setting fiat currency

- lib/state/appStore.ts
- pages/settings/wallets/EditWallet.tsx
Fixes #118
Also fixes Reset. Both will now redirect the user to the `/onboarding` screen.
> fix: allow deleting last wallet

- components/DualCurrencyInput.tsx
- pages/send/LNURLPay.tsx
- pages/send/PaymentSuccess.tsx
- pages/send/Send.tsx
Fixes #132 
Testing: 
- Without comment: LNURL1DP68GURN8GHJ7ER9D4HJUMRWVF5HGUEWVDHK6TMVDE6HYMRS9A2825R5292QMLWN6N
- With comment: LNURL1DP68GURN8GHJ7ER9D4HJUMRWVF5HGUEWVDHK6TMVDE6HYMRS9A5HJSFKGFZQYTNWTU
> feat: improve handling for fixed amount LNURLs

- app/_layout.tsx
- components/DualCurrencyInput.tsx
- components/FocusableCamera.tsx
- components/QRCodeScanner.tsx
- components/Receiver.tsx
- hooks/useHandleLinking.ts
- pages/Wildcard.tsx
- pages/send/ConfirmPayment.tsx
- pages/send/LNURLPay.tsx
- pages/send/PaymentSuccess.tsx
- pages/send/Send.tsx
- pages/settings/wallets/WalletConnection.tsx
- Delay start of camera for link intents
- Improve handling of human readable payment information (e.g. lightning:hello@getalby.com should display as hello@getalby.com)
- Fixes #128
- Fixes #83
To simulate opens during development:
```
npx uri-scheme open exp://127.0.0.1:8081/--/[LIGHTNING_ADDRESS] --android
npx uri-scheme open exp://127.0.0.1:8081/--/[LNURL] --android
npx uri-scheme open exp://127.0.0.1:8081/--/[BOLT11INVOICE] --android
```
- lightning:hello@getalby.com
- bitcoin:bitcoinaddress?lightning=lnbc1...
- lightning:lnurl
- lightning:invoice
> fix: improve linking

- components/AlbyBanner.tsx
- lib/state/appStore.ts
- pages/settings/wallets/EditWallet.tsx
- Fixes `getLastAlbyPayment` return type 
- Adds `flex-1` to Alby Banner
- Styles capabilities warning in wallet settings (is this even needed after #144?)
<table>
<tr>
<td>
</td>
<td>
</tr>
</table>
> chore: minor improvements

- app/(app)/_layout.tsx
- app/_layout.tsx
- pages/Onboarding.tsx
- pages/Unlock.tsx
Move onboarding check to inner layout to prevent any route updates before the rootNavigationState is available. 
Prevents "white screen of ☠️" for new users. :see_no_evil:
> fix: onboarding state

- lib/lnurl.ts
> fix: follow redirects when resolving lightning addresses

- lib/constants.ts
Removes `get_info` from the required capabilities, since `get_info` should always be available.
> fix: remove get_info from required capabilities

- app/(app)/withdraw/index.js
- components/DismissableKeyboardView.tsx
- components/Icons.tsx
- hooks/__tests__/useHandleLinking.ts
- hooks/useHandleLinking.ts
- lib/link.ts
- lib/lnurl.ts
- pages/receive/Receive.tsx
- pages/withdraw/Withdraw.tsx
Fixes #6 
Adds LNURL Withdraw
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
> feat: add lnurl withdrawal

- app/_layout.tsx
- lib/state/appStore.ts
- lib/useColorScheme.tsx
- pages/settings/Settings.tsx
> fix: store theme in app store and secure storage

- pages/Unlock.tsx
> fix: show auth prompt only once

- app.json
> chore: specify lsminimumsystemversion to avoid app store warnings

- app.json
Expo linking prefers the first value in the schemes array. Given we offer more support for `lightning:` links than `bitcoin:` it's good to have `lightning:` as preferred
> chore: set preferred scheme to lightning

- hooks/__tests__/useHandleLinking.ts
- lib/constants.ts
- lib/link.ts
Fixes #162 and also an issue where scanning `alby:hello@getalby.com` QRs result in `Failed to decoide payment request errors`
> fix: check for ln address and bolt11 before navigating to send

- components/QRCodeScanner.tsx
This is logged when a QR is scanned:
`Warning: Cannot update a component (SetupWallet) while rendering a different component (QRCodeScanner). To locate the bad setState() call inside QRCodeScanner, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`
Updater functions run during rendering, and that causes state updates in the parent as we are calling `onScanned`, so this moves that out to check `isScanning` and then proceed so that the logic is same but it is just moved outside the updater function
> fix: prevent state updates in parent while rendering qrcodescanner

- components/QRCodeScanner.tsx
The camera used to be active even after switching to contacts, this change checks if the screen in which the `QRCodeScanner` is present is focussed and only then renders the `FocusableCamera`
> fix: toggle camera only when screen is focussed

- components/QRCode.tsx
This makes QR codes more reliable across different scanners. [More info](https://www.qrcode-tiger.com/qr-code-error-correction)
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
> chore: add high error correction level to qr codes

- app/_layout.tsx
- package.json
- yarn.lock
During development, often the Stack.Screen goes down, interfering with the view. I found that the SafeArea we are using is from react-native, but expo has it's own safe area: https://docs.expo.dev/versions/latest/sdk/safe-area-context/ and replacing with that fixes the issue.
<table><tr><td>
> fix: use expo recommended safearea

- pages/Transaction.tsx
Fixes #212
The error happens because `boost.ts` is 0 and that causes `boost.ts && <TransactionDetailRow />` to render 0 causing the Text should be rendering within <Text> error.
This also fixes the boostagram types allowing them to be more flexible as different Podcast Clients do differently.
> fix: boostagram types and 0 handling

- app.json
- lib/link.ts
- pages/settings/Wallets.tsx
- pages/settings/wallets/SetupWallet.tsx
Fixes #75 
You can now scan/click `nostr+walletconnect:` urls and it redirects to Alby Go and sets a new wallet (it only goes till name your wallet page, we can click cancel and terminate the process if the user doesn't wish to add a wallet)
> feat: support nwc connection urls

- components/ui/card.tsx
- pages/settings/wallets/EditWallet.tsx
- pages/settings/wallets/SetupWallet.tsx
Fixes https://github.com/getAlby/go/issues/172
<table><tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr></table>
> fix: gracefully handle missing permissions

- components/Alert.tsx
- pages/send/ConfirmPayment.tsx
- pages/settings/Security.tsx
- pages/settings/wallets/EditWallet.tsx
- pages/settings/wallets/SetupWallet.tsx
- pages/withdraw/Withdraw.tsx
Adds alert component
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
> feat: add alert component

- app/_layout.tsx
- components/Alert.tsx
- components/DualCurrencyInput.tsx
- components/Icons.tsx
- components/QRCodeScanner.tsx
- components/ToastConfig.tsx
- components/ui/dialog.tsx
- package.json
- pages/Home.tsx
- pages/Transaction.tsx
- pages/Transactions.tsx
- pages/receive/Receive.tsx
- pages/send/AddressBook.tsx
- pages/send/Send.tsx
- pages/settings/Security.tsx
- pages/settings/Settings.tsx
- pages/settings/Wallets.tsx
- pages/settings/wallets/EditWallet.tsx
- pages/settings/wallets/SetupWallet.tsx
- pages/withdraw/Withdraw.tsx
- yarn.lock
Fixes #29
Needs a new update of popicons as the current version doesn't apply width and height attributes to the svg properly.
See https://github.com/uxthings/popicons/issues/6
> feat: use popicons 🎈 

- pages/settings/wallets/SetupWallet.tsx
This removes the back button in the header, if you cancel/finish setup
Note: for some reason, this cannot be observed in Expo Go but the production build also has this issue.
<table><tr><td>
</td><td>
</td></tr></table>
> chore: dismiss all before returning home

- components/QRCodeScanner.tsx
#196 fixed the `Cannot update a component` warning but introduced a big error where the scanner would stop scanning if a faulty qr is scanned instead oif showing an error and proceeding to scan further. This PR aims to resolve this
> fix: qr scanner on failure

- components/Icons.tsx
- lib/state/appStore.ts
- pages/Home.tsx
- pages/settings/Wallets.tsx
- pages/settings/wallets/EditWallet.tsx
- pages/settings/wallets/LightningAddress.tsx
- pages/settings/wallets/RenameWallet.tsx
Fixes #165
Also fixes https://github.com/getAlby/go/pull/230#discussion_r1897255697
> feat: simplify wallet renaming flow

- app.json
- app/_layout.tsx
- lib/state/appStore.ts
- package.json
- yarn.lock
Previously we used to set the theme to "system" which is not a valid option (light | dark) which results in the theme switching from dark to light due to invalid setting, now we set our theme variable in the app store to the device theme the first time, and post that we set the theme of the app from the app store.
Also see https://github.com/facebook/react-native/issues/31806#issuecomment-873670374 to get device theme
> fix: get theme from device

- pages/Home.tsx
- pages/Transactions.tsx
- pages/send/PaymentSuccess.tsx
- pages/settings/wallets/SetupWallet.tsx
Fixes screen header's right buttons not working due to issue in expo-router: https://github.com/expo/expo/issues/29489
Changes `onPress` to `onPressIn`
> fix: screen header buttons

- pages/receive/Receive.tsx
Fixes #240
We have faced multiple issues reg QR code readability, so it's best to remove the logo for now and think of adding it somewhere else.
> chore: remove logo from qr codes

- components/Alert.tsx
- components/ui/card.tsx
Fixes #251 
Add a boolean wrapText prop to CardTitle component that when set allows the text to wrap.
This pull request makes the assumption that wrapping text should not be the default, and is only desired on Alerts. If the intention is all CardTitle components should have text wrapped then numberOfLines can be removed.
In this screenshot the Alert title has wrapText prop set, while the title below does not.
This is my first pull request for this project. Any feedback is helpful!
> Fix: Wrap error title

- .github/workflows/pull_requests.yml
- .github/workflows/release.yml
> fix: add google services json to workflow

- lib/merchants.ts
- pages/send/Send.tsx
This adds support for merchant QRs which need to be converted into lightning addresses. Thanks to https://github.com/GaloyMoney/galoy-client/pull/331
**You can try using this QR:**
**Or paste:**
`00020129530023ZA.CO.ELECTRUM.PICKNPAY0122RD2HAK3KTI53EC/CONFIRM520458125303710540115802ZA5916CRYPTOQRTESTSCAN6002CT63049BE2`
> feat: add support for pick n pay QRs

- pages/settings/wallets/EditWallet.tsx
improving accuracy of text to prevent users having unnecessary fear about "deletion", since they are wallet connections and not wallets themselves.
> fix: update delete wallet copy

- app/_layout.tsx
- context/UserInactivity.tsx
- hooks/useBalance.ts
- hooks/useInfo.ts
- hooks/useTransactions.ts
- lib/createNwcFetcher.ts
- lib/state/appStore.ts
Fixes https://github.com/getAlby/go/issues/278
- Does not show toast when error
- Remove unreliable `useConnectionChecker` code which can show a toast even if it was just a network error and the app connection is actually fine
- Replace unnecessary secure storage variable with in memory variable for checking if unlock page should be shown
> fix: do not show error toasts when in-progress nwc request was backgrounded

- hooks/useGetFiatAmount.ts
- lib/constants.ts
Currently we don't refresh btc rates which might result in outdated btc rates if user stays for very long. This PR makes sure it is updated every 5 minutes
> fix: refresh btc rate every 5 minutes

- components/FocusableCamera.tsx
Fixes #292 
Related Issues:
https://github.com/expo/expo/issues/35386
https://github.com/expo/expo/issues/34896
> fix: manually wait for camera ready before initializing

- pages/settings/wallets/ConnectWallet.tsx
This add ability to switch wallets which was not previously possible due to `NotSupportedView` blocking the wallet switcher
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
> fix: add option to switch wallets in NWA flow

- app/(app)/send/manual.js
- pages/send/Manual.tsx
- pages/send/Send.tsx
Hey folks! I spotted a little navigation quirk in the Send screen, hitting the back button from the Amount input dumps you back to the main screen, while Contacts and Paste return you to the QR scanner. It felt jarring, so I added a `BackHandler` to `Send.tsx` to catch the back press when `keyboardOpen` is true, flipping it to false to keep you in the QR flow. Tested it on my Android 14(API 34).
1. Open Alby Go and tap “Send.”
2. Hit the “Amount” button to bring up the input view.
3. Press the hardware back button : before this fix, you’d land on the main screen instead of the QR scanner.
- **Before**: [Video](https://drive.google.com/file/d/1eZ0d_i86M13SQP62a1Wgwn5rFwlPunHX/view?usp=sharing) : Back press kicks you to the main screen
- **After**: …
> fix: Return to QR Scanner on Back from Amount Input

- components/TransactionItem.tsx
Fixes #329
We currently decide the transaction title based on non-NIP-47 compliant field (`state`), which causes nip47 wallets without `state` property to show wrong information in the title like `"Failed"` instead of `"Sent"`
> fix: use transaction type instead of state for tx title
