components/Icons.tsx
lib/state/appStore.ts
pages/Home.tsx
pages/settings/Settings.tsx
pages/settings/Wallets.tsx
pages/settings/wallets/EditWallet.tsx
pages/settings/wallets/WalletConnection.tsx

@rolznz Can you please give this a try on iOS? I noticed in some of your videos that the spacing here is a bit off and buttons jumping around when you select a different wallet. 
On Android it seems fine though...

fix: wallet list spacing

---

app/_layout.tsx
components/Icons.tsx
pages/settings/Settings.tsx

Simply toggle between light / dark theme by clicking the setting.

feat: theme switcher

---

components/LinearGradient.tsx
components/QRCode.tsx
components/ui/button.tsx

fixes QR code gradient, and shadows on button gradient variant
alternative to https://github.com/getAlby/alby-mobile/pull/52

UI fixes (v2)

---

README.md
app.json
package.json
pages/settings/Settings.tsx

fix: rename

---

pages/Transaction.tsx
pages/Transactions.tsx

fix: transaction lists

---

.github/workflows/main.yml
.github/workflows/pull_requests.yml
.github/workflows/release.yml
app.json
eas.json

build android apks

---

components/ui/button.tsx
pages/send/Send.tsx

Fixes text overflow on buttons.

fix: button behavior on smaller screens

---

zapstore.yaml

Publish the app releases on zap.store , fixes #62 
Docs will be added with #82

feat: zapstore

---

pages/settings/Wallets.tsx

In settings after I select a different wallet move to the home screen.

feat: improve switch wallet ux

---

pages/settings/wallets/RenameWallet.tsx

- Update font style of input on Rename Wallet

fix: minor ui improvements

---

.github/workflows/pull_requests.yml
.github/workflows/release.yml
eas.json

autoIncrement true for apk builds

---

pages/send/ConfirmPayment.tsx
pages/send/PaymentSuccess.tsx
pages/send/Send.tsx

fix: formatting + font styles

---

app/_layout.tsx
components/Icons.tsx
components/ToastConfig.tsx
pages/settings/Wallets.tsx
pages/settings/wallets/WalletConnection.tsx

fix: positioning of toasts, icon

---

components/AlbyBanner.tsx
lib/constants.ts
lib/lnurl.ts
lib/state/appStore.ts
pages/Home.tsx
pages/send/ConfirmPayment.tsx
pages/send/LNURLPay.tsx
pages/send/PaymentSuccess.tsx
pages/send/Send.tsx
pages/settings/Settings.tsx

- adds (internal) `amount` param to lnurl screen
- fixes #138

feat: alby banner

---

lib/constants.ts
pages/settings/wallets/WalletConnection.tsx

fix: validate capabilities in connection secret during setup

---

lib/constants.ts
package.json
pages/settings/FiatCurrency.tsx
yarn.lock

fetch supported currency list from getalby.com
remove currency-list npm package
introduce search bar to search for currencies
add caching to api call
https://github.com/user-attachments/assets/abfc1a6e-018d-4175-b6d7-77d38156c6bd

feat: load currency list from api & search

---

animations/Paid.tsx
pages/receive/ReceiveSuccess.tsx
pages/send/PaymentSuccess.tsx

Better handling of long descriptions on small screens

fix: success layout

---

components/DualCurrencyInput.tsx
lib/constants.ts

fix: validate input numbers

---

pages/receive/Receive.tsx

<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

fix: allow users to withdraw when ln address is not set

---

pages/send/AddressBook.tsx

Contacts page isn't scrollable, this PR adds ScrollView to fix that

fix: make contacts screen scrollable

---

components/Icons.tsx
components/ui/card.tsx
lib/state/appStore.ts
pages/send/AddressBook.tsx
pages/settings/address-book/NewAddressBookEntry.tsx
pages/settings/wallets/EditWallet.tsx

Adds delete icon in the contacts screen
Also adds icons to contacts
Updates the card component 
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>

feat: delete contacts

---

app/(app)/settings/wallets/[id]/lightning-address.js
package.json
pages/receive/Receive.tsx
pages/settings/wallets/LightningAddress.tsx
yarn.lock

Fixes https://github.com/getAlby/go/issues/134
Especially important to ensure users don't lose funds by setting a lightning address they do not own and then not receiving the funds.

feat: verify ownership of lightning address

---

pages/Home.tsx

fixes https://github.com/getAlby/go/issues/213

feat: refresh balance

---

components/icons/FailedTransaction.tsx
components/icons/ReceivedTransaction.tsx
components/icons/SentTransaction.tsx
pages/Transaction.tsx
pages/Transactions.tsx

Fixes #211 
Adds new icons and makes some UI fixes (font-sizing, spacing etc.) to make it look similar to the extension/hub (finally \o/)
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: add new icons for transactions

---

pages/send/ConfirmPayment.tsx
pages/withdraw/Withdraw.tsx

Fixes #220 
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>

feat: show wallet name in payment confirmation and withdraw screen

---

pages/Home.tsx

Fixes #214
(Clicking on wallet name takes you to Manage Wallets)

feat: show active wallet name

---

lib/state/appStore.ts
pages/Home.tsx

Fixes #200
Now we store a `balanceDisplayMode` field in app store and secure-storage

fix: persist balance display mode

---

components/icons/PendingTransaction.tsx
pages/Transaction.tsx
pages/Transactions.tsx

chore: add pending icon

---

components/icons/FailedTransaction.tsx
components/icons/PendingTransaction.tsx
components/icons/ReceivedTransaction.tsx
components/icons/SentTransaction.tsx

feat: update transaction icon colors

---

components/HelpModal.tsx
pages/settings/Notifications.tsx
pages/settings/Security.tsx

Fixes text not shown in dark mode in notifications screen,and unifies code.

chore: replace RN Text with Text component

---

assets/android/MessagingService.kt
assets/ios/NotificationService.m

chore: shorten and unify notification text across platforms

---

pages/settings/wallets/RenameWallet.tsx

fix: do not allow setting empty name while renaming

---

.github/workflows/pull_requests.yml
.github/workflows/release.yml
app.config.js
app/_layout.tsx
metro.config.js
package.json
yarn.lock

Fixes https://github.com/getAlby/go/issues/74
Adds sentry

chore: add sentry for error tracking

---

components/CreateInvoice.tsx
components/TransactionItem.tsx
hooks/useGetFiatAmount.ts
lib/constants.ts
lib/createNwcFetcher.ts
lib/initiatePaymentFlow.ts
lib/link.ts
lib/state/appStore.ts
lib/utils.ts
package.json
pages/Transaction.tsx
pages/Transactions.tsx
pages/receive/ReceiveSuccess.tsx
pages/send/ConfirmPayment.tsx
pages/send/Manual.tsx
pages/send/Send.tsx
pages/settings/wallets/ConnectWallet.tsx
pages/settings/wallets/SetupWallet.tsx
yarn.lock

Upgrades `@getalby/lightning-tools`, `@getalby/sdk`

chore: update @getalby packages
